### ISSUE TITLE
can't run gulp after fresh clone

### ISSUE THREAD

**Issue by haswillb** [vulpino/jolteon#3]
I get this error after a fresh clone :/

``` js
/Users/willb/repos/jolteon/gulpfile.js:16
const gulp = require('gulp')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at execute (/usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:24:18)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp-cli/index.js:150:63)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:192:16)
```

**Comment by haswillb** [comment]
It sounds like it's a problem with the node version.

**Comment by fluffgfx** [comment]
What version node are you running?

You could try renaming the gulpfile to gulpfile.babel.js which will run it through babel before parsing it. I think that should fix older node versions acting up, but the start time will be considerably longer.

**Comment by haswillb** [comment]
I was using node 0.12. Upgrading fixed the issue :-)
